/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface RoyaltyDistributorInterface extends ethers.utils.Interface {
  functions: {
    "addReceiver(address,uint256)": FunctionFragment;
    "cumulativePercentage()": FunctionFragment;
    "distributeBalance()": FunctionFragment;
    "owner()": FunctionFragment;
    "receiverCount()": FunctionFragment;
    "receivers(uint256)": FunctionFragment;
    "receiversArrayLength()": FunctionFragment;
    "removeReceiver(address,uint256)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addReceiver",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cumulativePercentage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "distributeBalance",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "receiverCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "receivers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "receiversArrayLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeReceiver",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "addReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cumulativePercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "receiverCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "receivers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "receiversArrayLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
    "PaymentReceived(uint256)": EventFragment;
    "ReceiverAdded(address,uint256)": EventFragment;
    "ReceiverRemoved(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PaymentReceived"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ReceiverAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ReceiverRemoved"): EventFragment;
}

export type OwnershipTransferredEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>;

export type PaymentReceivedEvent = TypedEvent<
  [BigNumber] & { amount: BigNumber }
>;

export type ReceiverAddedEvent = TypedEvent<
  [string, BigNumber] & { wallet: string; percentage: BigNumber }
>;

export type ReceiverRemovedEvent = TypedEvent<
  [string, BigNumber] & { wallet: string; percentage: BigNumber }
>;

export class RoyaltyDistributor extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: RoyaltyDistributorInterface;

  functions: {
    addReceiver(
      wallet: string,
      percentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    cumulativePercentage(overrides?: CallOverrides): Promise<[BigNumber]>;

    distributeBalance(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    receiverCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    receivers(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { wallet: string; percentage: BigNumber }>;

    receiversArrayLength(overrides?: CallOverrides): Promise<[BigNumber]>;

    removeReceiver(
      wallet: string,
      percentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  addReceiver(
    wallet: string,
    percentage: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  cumulativePercentage(overrides?: CallOverrides): Promise<BigNumber>;

  distributeBalance(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  receiverCount(overrides?: CallOverrides): Promise<BigNumber>;

  receivers(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[string, BigNumber] & { wallet: string; percentage: BigNumber }>;

  receiversArrayLength(overrides?: CallOverrides): Promise<BigNumber>;

  removeReceiver(
    wallet: string,
    percentage: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addReceiver(
      wallet: string,
      percentage: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    cumulativePercentage(overrides?: CallOverrides): Promise<BigNumber>;

    distributeBalance(overrides?: CallOverrides): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    receiverCount(overrides?: CallOverrides): Promise<BigNumber>;

    receivers(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { wallet: string; percentage: BigNumber }>;

    receiversArrayLength(overrides?: CallOverrides): Promise<BigNumber>;

    removeReceiver(
      wallet: string,
      percentage: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    "PaymentReceived(uint256)"(
      amount?: null
    ): TypedEventFilter<[BigNumber], { amount: BigNumber }>;

    PaymentReceived(
      amount?: null
    ): TypedEventFilter<[BigNumber], { amount: BigNumber }>;

    "ReceiverAdded(address,uint256)"(
      wallet?: string | null,
      percentage?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { wallet: string; percentage: BigNumber }
    >;

    ReceiverAdded(
      wallet?: string | null,
      percentage?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { wallet: string; percentage: BigNumber }
    >;

    "ReceiverRemoved(address,uint256)"(
      wallet?: string | null,
      percentage?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { wallet: string; percentage: BigNumber }
    >;

    ReceiverRemoved(
      wallet?: string | null,
      percentage?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { wallet: string; percentage: BigNumber }
    >;
  };

  estimateGas: {
    addReceiver(
      wallet: string,
      percentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    cumulativePercentage(overrides?: CallOverrides): Promise<BigNumber>;

    distributeBalance(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    receiverCount(overrides?: CallOverrides): Promise<BigNumber>;

    receivers(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    receiversArrayLength(overrides?: CallOverrides): Promise<BigNumber>;

    removeReceiver(
      wallet: string,
      percentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addReceiver(
      wallet: string,
      percentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    cumulativePercentage(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    distributeBalance(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    receiverCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    receivers(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    receiversArrayLength(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    removeReceiver(
      wallet: string,
      percentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
