import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useWallet } from 'use-wallet'
import toast, { Toaster } from 'react-hot-toast'
import { useTransition, animated } from 'react-spring'

import { ENSSection, TxStatesSection, GMModeSection, WalletConnectSection } from '../components/web3FeatureSections'
import AdminPanel from '../components/adminPanel'
import Navbar from '../components/navbar'
import ChestCloseup from '../components/ChestCloseup'
import { useEffect, useState } from 'react'
import { useMintAvailable } from '../hooks/useMintAvailable'

const BACKGROUND_IMAGES = {
  closeup: '/assets/s1-chest-background.png',
  open: '/assets/s1-open.gif',
  closed: '/assets/s1-closed.gif',
}

const Home: NextPage = () => {
  const wallet = useWallet()
  const { status, networkName } = wallet

  const { isAvailable, isLoading } = useMintAvailable()

  const [contractState, setContractState] = useState(isLoading || !isAvailable ? 'closed' : 'open')
  const [state, setState] = useState(contractState)

  useEffect(() => {
    if (state === 'closeup' && status !== 'connected') setState(contractState)
  }, [status, state, contractState])

  const renderState = (): React.ReactFragment => {
    switch (state) {
      case 'closeup':
        return <ChestCloseup />
      case 'open':
        return (
          <div
            className="h-full max-h-screen min-w-screen"
            onClick={(e) =>
              status === 'connected' ? setState('closeup') : toast('Connect your wallet.', { icon: '👝' })
            }
          ></div>
        )
      case 'closed':
        return (
          <div
            className="h-full max-h-screen min-w-screen"
            onClick={(e) => toast('All potions have been collected for today. Come back tomorrow.', { icon: '💤' })}
          ></div>
        )
    }
  }

  return (
    <div
      className="min-h-screen m-auto min-w-screen"
      style={{
        backgroundImage: `url(${BACKGROUND_IMAGES[state]})`,
        backgroundPosition: '45% center',
        backgroundSize: 'cover',
      }}
    >
      <Head>
        <title>Web 3 Starter Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Toaster position="bottom-right" reverseOrder={true} />
      <Navbar />
      <div style={{ height: '90vh' }}>{renderState()}</div>
    </div>
  )
}

export default Home
